// 1. Go to https://beeceptor.com/crud-api/
// 2. Click "Create CRUD API" button
// 3. It will generate a url in the next page. It should end with "...free.beeceptor.com/api/users"
// 4. Copy the url below as a string. Do not include anything after ".com"
const url = "https://ca59c0975fefbafe5828.free.beeceptor.com";

const testUser = {
  firstName: "test first name",
  lastName: "test last name",
  location: "test city",
};

const anotherUser = {
  firstName: "another first name",
  lastName: "another last name",
  location: "another city",
};

// ------------------------------------------
// Create a new user

// 5. Follow the instructions on the homepage. Use a POST request to create a new user. Use one of the user objects above in your body.
fetch(`${url}/api/users/`, {
  method: "POST",
  body: JSON.stringify(testUser),
})
  .then((response) => response.json())
  .then((result) => console.log("Request successful", result))
  .catch((error) => console.log("Request failed", error));

// 6. Make sure to use then and catch chains properly to display the results in the console.
// 7. Copy the id generated by the API for this user into the `userId` variable below

const userId = "8fe9da01b86415cea93e";

// ------------------------------------------
// Get all users

// 8. Use fetch to get all users
fetch(`${url}/api/users/`)
  .then((response) => response.json())
  .then((result) => console.log("Getting all users", result))
  .catch((error) => console.log("Request to get users failed", error));

// ------------------------------------------
// Get a specific user by id

// 9. Use fetch to get a specific user with the id copied above
fetch(`${url}/api/users/${userId}`)
  .then((response) => response.json())
  .then((result) => console.log("Getting user id", result))
  .catch((error) => console.log("Request to get user's id failed", error));

// ------------------------------------------
// Update a specific user by id

// 10.Update the user with id above with another user
fetch(`${url}/api/users/${userId}`, {
  method: "PUT",
  body: JSON.stringify(anotherUser),
})
  .then((response) => response.json())
  .then((result) => console.log("Getting user id", result))
  .catch((error) => console.log("Request to get user's id failed", error));

// ------------------------------------------
// Delete a specific user by id

// 11. Delete all the users one at a time. Use get all users request above to get the users and find their ids.
fetch(`${url}/api/users/${"0ca4621a704081a9dce3"}`, {
  method: "DELETE",
})
  .then((response) => response.json())
  .then((result) => console.log("All users were successfully deleted", result))
  .catch((error) => console.log("All users deletion failed", error));

fetch(`${url}/api/users/${"d47d63377867e56a43f5"}`, {
  method: "DELETE",
})
  .then((response) => response.json())
  .then((result) => console.log("All users were successfully deleted", result))
  .catch((error) => console.log("All users deletion failed", error));
